# Infopage module - creates GitHub repository with info page

# Create GitHub repository for info page
resource "github_repository" "info_page" {
  name        = "information-page"
  description = "Repository information page generated by Terraform"
  visibility  = "public"
  auto_init   = true
  
  pages {
    source {
      branch = "main"
      path   = "/"
    }
  }
}

# Create README.md file in the repository
resource "github_repository_file" "readme_md" {
  repository = github_repository.info_page.name
  branch     = "main"
  file       = "README.md"
  
  content = <<-EOT
# Repository Information

*Generated on: ${timestamp()}*

## Repositories

| Repository | Type | Language | Repository Link | Page Link |
|------------|------|----------|-----------------|-----------|
%{for name, repo in var.repository_data~}
| ${repo.name} | ${repo.type} | ${repo.language} | [GitHub](${repo.repo_url}) | %{if repo.has_page && repo.page_url != null && repo.page_url != "Pending"~}[View Page](${repo.page_url})%{else~}%{if repo.has_page && repo.page_url == "Pending"~}*Page Pending*%{else~}*No Page*%{endif~}%{endif~} |
%{endfor~}

**Total repositories:** ${length(var.repository_data)}

---
*This page was generated automatically using Terraform*
  EOT
  
  overwrite_on_create = true
}
